[workspace]
name = "acados_vendor_ros2"
channels = [
  "http://localhost:8000/general",
  "https://prefix.dev/robostack-kilted",
  "https://prefix.dev/conda-forge",
]
platforms = ["linux-64", "linux-aarch64"]
preview = ["pixi-build"]

[dependencies]
acados_vendor_ros2 = { path = "." }
mise = "*"

[package]
name = "acados_vendor_ros2"
version = "1.0.4"
description = "Vendored version of acados."
license = "Apache-2.0"
authors = ["Thibault Poignonec <thibault.poignonec@gmail.com>"]

[package.build.backend]
name = "pixi-build-ros-gr"
version = "*"

[package.build.config]
mode = "pixi-native"
build-type = "ament_cmake"
distro = "kilted"

build-number = 1
[package.build-dependencies]
patchelf = "*"

[package.host-dependencies]
ros-kilted-ament-cmake = "*"
ros-kilted-ament-cmake-python = "*"
ros-kilted-ament-cmake-vendor-package = "*"
pkg-config = "*"
git = "*"
make = "*"
gfortran = "*"
cython = "*"
numpy = "*"

[package.run-dependencies]
python = "*"
numpy = "*"
scipy = "*"
casadi = "*"
